
server:
  port: 8081
  servlet:
    context-path: /dev/api/${spring.application.name}


spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/PenHub


  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect=org: org.hibernate.dialect.MySQLDialect

